### ISSUE TITLE
Cannot connect to the postgresql

### ISSUE THREAD

**Issue by duythinh26** [dhij/go-next-ts_chat#3]
I don't know what I'm doing wrong here but when I run the command and it said I can't connect because the target machine refused it. I did exactly anything you did in the tutorial until going to this part
![image](https://github.com/dhij/go-next-ts_chat/assets/67096386/f33dff5e-5a1b-455a-bebb-6be55f3e2df8)

**Comment by dhij** [comment]
Do you have postgres running on your machine? You would either have to install that locally or run a postgres container on Docker. Let me know if you have trouble doing that.

**Comment by duythinh26** [comment]
I solved the problem, thank you.
